import { afterAll, beforeAll, describe, expect, inject, it } from "vitest";

import { createPrismaClient } from "@repo/database";
import type { PrismaClient } from "@repo/database";

import { createAuth } from "../src/server";
import type { Auth, VerificationEmail } from "../src/server";

/**
 * Better Auth against a real Postgres: sign-up writes the users/accounts rows, the
 * verification mail goes through OUR callback (outbox in the API), and sessions resolve.
 */
let prisma: PrismaClient;
let auth: Auth;
const sentMails: VerificationEmail[] = [];

beforeAll(() => {
  prisma = createPrismaClient({ connectionString: inject("databaseUrl") });
  auth = createAuth({
    prisma,
    secret: "test-secret-test-secret-test-secret-1234",
    baseURL: "http://localhost:4000",
    trustedOrigins: ["http://localhost:3000"],
    sendVerificationEmail: (mail) => {
      sentMails.push(mail);
      return Promise.resolve();
    },
  });
});

afterAll(async () => {
  await prisma.$disconnect();
});

const unique = () => `user-${crypto.randomUUID()}@example.com`;

describe("sign up", () => {
  it("creates the user with the default role, stores the extra fields and requests exactly one verification mail", async () => {
    const email = unique();
    sentMails.length = 0;

    const result = await auth.api.signUpEmail({
      body: {
        name: "Bat Bold",
        email,
        password: "correct-horse-battery",
        employeeCode: `EMP-${crypto.randomUUID().slice(0, 8)}`,
        department: "HR",
      },
    });

    expect(result.user.email).toBe(email);
    // Email must be verified before a session is issued.
    expect(result.token).toBeNull();

    const stored = await prisma.user.findUnique({ where: { email } });
    expect(stored).toMatchObject({ name: "Bat Bold", role: "member", department: "HR" });
    expect(stored?.emailVerified).toBe(false);
    // UUID v7 generated by Postgres (generateId: false)
    expect(stored?.id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-/);

    const accounts = await prisma.account.findMany({ where: { userId: stored?.id ?? "" } });
    expect(accounts).toHaveLength(1);
    expect(accounts[0]?.providerId).toBe("credential");

    expect(sentMails).toHaveLength(1);
    expect(sentMails[0]?.user.email).toBe(email);
    expect(sentMails[0]?.url).toContain("/api/auth/verify-email");
    expect(sentMails[0]?.token.length).toBeGreaterThan(10);
  });

  it("refuses to sign in before the email is verified", async () => {
    const email = unique();
    await auth.api.signUpEmail({
      body: { name: "Unverified", email, password: "correct-horse-battery" },
    });

    await expect(
      auth.api.signInEmail({ body: { email, password: "correct-horse-battery" } }),
    ).rejects.toMatchObject({ status: "FORBIDDEN" });
  });

  it("issues a session after verification and resolves it from the cookie header", async () => {
    const email = unique();
    sentMails.length = 0;
    await auth.api.signUpEmail({
      body: { name: "Verified", email, password: "correct-horse-battery" },
    });
    const token = sentMails[0]?.token;
    expect(token).toBeDefined();

    // autoSignInAfterVerification: the verify call returns Set-Cookie headers.
    const verifyResponse = await auth.api.verifyEmail({
      query: { token: token ?? "" },
      asResponse: true,
    });
    const setCookie = verifyResponse.headers.get("set-cookie") ?? "";
    expect(setCookie).toContain("better-auth.session_token");

    const cookie = setCookie
      .split(",")
      .map((part) => part.split(";")[0]?.trim() ?? "")
      .filter((part) => part.startsWith("better-auth."))
      .join("; ");
    const session = await auth.api.getSession({ headers: new Headers({ cookie }) });

    expect(session?.user.email).toBe(email);
    expect(session?.user.emailVerified).toBe(true);
    expect(session?.user.role).toBe("member");
  });
});
