import { afterAll, beforeAll, describe, expect, inject, it } from "vitest";

import { createPrismaClient } from "@repo/database";
import type { PrismaClient } from "@repo/database";
import { DEFAULT_ROLE } from "@repo/validation";
import type { Role } from "@repo/validation";

import { createAuth } from "../src/server";
import type { Auth, SessionUser, VerificationEmail } from "../src/server";

/**
 * Better Auth against a real Postgres: public sign-up is off, users come only from the admin
 * plugin's `createUser`, the verification mail goes through OUR callback (outbox in the API),
 * and sessions resolve from the cookie.
 */
let prisma: PrismaClient;
let auth: Auth;
const sentMails: VerificationEmail[] = [];

beforeAll(() => {
  prisma = createPrismaClient({ connectionString: inject("databaseUrl") });
  auth = createAuth({
    prisma,
    secret: "test-secret-test-secret-test-secret-1234",
    baseURL: "http://localhost:4000",
    trustedOrigins: ["http://localhost:3000"],
    sendVerificationEmail: (mail) => {
      sentMails.push(mail);
      return Promise.resolve();
    },
  });
});

afterAll(async () => {
  await prisma.$disconnect();
});

const PASSWORD = "correct-horse-battery";
const UUID_V7 = /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-/;

const unique = () => `user-${crypto.randomUUID()}@example.com`;

/** Server-side admin call (no headers): the only way a user gets created. */
const createUser = (email: string, name: string) =>
  auth.api.createUser({ body: { email, password: PASSWORD, name, role: DEFAULT_ROLE } });

/** The `better-auth.*` cookies of a response, as the `Cookie` header of the next request. */
const cookieHeaderFrom = (response: Response) =>
  response.headers
    .getSetCookie()
    .map((cookie) => cookie.split(";")[0] ?? "")
    .filter((cookie) => cookie.startsWith("better-auth."))
    .join("; ");

const sessionWithCookie = (cookie: string) =>
  auth.api.getSession({ headers: new Headers({ cookie }) });

const sessionFor = (response: Response) => sessionWithCookie(cookieHeaderFrom(response));

/** A verified user with the given role, signed in: its id and the cookie for later `getSession` calls. */
const signedInAs = async (role: Role) => {
  const email = unique();
  const created = await auth.api.createUser({
    body: { email, password: PASSWORD, name: `Role ${role}`, role, data: { emailVerified: true } },
  });
  const response = await auth.api.signInEmail({
    body: { email, password: PASSWORD },
    asResponse: true,
  });
  expect(response.status).toBe(200);
  return { userId: created.user.id, cookie: cookieHeaderFrom(response) };
};

/** The seeded `role_permissions` join for a role as session grants, in catalog key order. */
const roleGrants = async (roleKey: Role) => {
  const rows = await prisma.rolePermission.findMany({
    where: { roleKey },
    include: { permission: true },
    orderBy: { permissionKey: "asc" },
  });
  return rows.map(({ permission }) => ({
    action: permission.action,
    subject: permission.modelName,
  }));
};

/** The `{ action, subject }` grant a catalog row maps to. */
const grantOf = async (key: string) => {
  const permission = await prisma.permission.findUniqueOrThrow({ where: { key } });
  return { action: permission.action, subject: permission.modelName };
};

describe("sign up", () => {
  it("is disabled: the public endpoint rejects and writes no user row", async () => {
    const email = unique();

    await expect(
      auth.api.signUpEmail({ body: { name: "Bat Bold", email, password: PASSWORD } }),
    ).rejects.toMatchObject({
      status: "BAD_REQUEST",
      body: { code: "EMAIL_PASSWORD_SIGN_UP_DISABLED" },
    });

    expect(await prisma.user.findUnique({ where: { email } })).toBeNull();
  });
});

describe("createUser (admin plugin, server-side)", () => {
  it("applies the default role when none is given and stores the name, a uuid v7 id and one credential account", async () => {
    const email = unique();

    // No `role` on purpose: the admin plugin's `defaultRole` must fill it in.
    const result = await auth.api.createUser({
      body: { email, password: PASSWORD, name: "Bat Bold" },
    });
    expect(result.user.email).toBe(email);

    const stored = await prisma.user.findUniqueOrThrow({ where: { email } });
    expect(stored).toMatchObject({ name: "Bat Bold", role: DEFAULT_ROLE, emailVerified: false });
    // UUID v7 generated by Postgres (generateId: false)
    expect(stored.id).toMatch(UUID_V7);

    const accounts = await prisma.account.findMany({ where: { userId: stored.id } });
    expect(accounts).toHaveLength(1);
    expect(accounts[0]?.providerId).toBe("credential");
  });

  it("rejects a role outside the role set and writes no user row", async () => {
    const email = unique();

    // The typed `role` field only admits configured keys; the endpoint validates `data.role`
    // on the same path, which is what an HTTP caller posting `role: "ceo"` hits.
    await expect(
      auth.api.createUser({
        body: { email, password: PASSWORD, name: "Nobody", data: { role: "ceo" } },
      }),
    ).rejects.toMatchObject({
      status: "BAD_REQUEST",
      body: { code: "YOU_ARE_NOT_ALLOWED_TO_SET_NON_EXISTENT_VALUE" },
    });

    expect(await prisma.user.findUnique({ where: { email } })).toBeNull();
  });
});

describe("email verification", () => {
  it("refuses to sign in before the email is verified", async () => {
    const email = unique();
    await createUser(email, "Unverified");

    await expect(
      auth.api.signInEmail({ body: { email, password: PASSWORD } }),
    ).rejects.toMatchObject({ status: "FORBIDDEN", body: { code: "EMAIL_NOT_VERIFIED" } });
  });

  it("sends exactly one mail through our callback, then verifies and issues a session", async () => {
    const email = unique();
    await createUser(email, "Verified");

    await auth.api.sendVerificationEmail({ body: { email } });

    const mails = sentMails.filter((mail) => mail.user.email === email);
    expect(mails).toHaveLength(1);
    expect(mails[0]?.user.name).toBe("Verified");
    expect(mails[0]?.url).toContain("/api/auth/verify-email");
    expect(mails[0]?.token.length).toBeGreaterThan(10);

    // autoSignInAfterVerification: the verify call returns Set-Cookie headers.
    const verifyResponse = await auth.api.verifyEmail({
      query: { token: mails[0]?.token ?? "" },
      asResponse: true,
    });
    expect(cookieHeaderFrom(verifyResponse)).toContain("better-auth.session_token");

    const session = await sessionFor(verifyResponse);
    expect(session?.user.email).toBe(email);
    expect(session?.user.emailVerified).toBe(true);
    expect(session?.user.role).toBe(DEFAULT_ROLE);
  });
});

describe("sessions", () => {
  it("signs in a user the admin created as verified and resolves the session from the cookie", async () => {
    const email = unique();
    await auth.api.createUser({
      body: {
        email,
        password: PASSWORD,
        name: "Pre-verified",
        role: DEFAULT_ROLE,
        data: { emailVerified: true },
      },
    });

    const signInResponse = await auth.api.signInEmail({
      body: { email, password: PASSWORD },
      asResponse: true,
    });
    expect(signInResponse.status).toBe(200);

    const session = await sessionFor(signInResponse);
    expect(session?.user.email).toBe(email);
    expect(session?.user.emailVerified).toBe(true);
    expect(session?.user.role).toBe(DEFAULT_ROLE);
  });

  it("resolves no session for a request without cookies", async () => {
    expect(await auth.api.getSession({ headers: new Headers() })).toBeNull();
  });
});

describe("session permissions (customSession)", () => {
  it("carries the role's grants from role_permissions as { action, subject } for a staff user", async () => {
    const { cookie } = await signedInAs("staff");
    const expected = await roleGrants("staff");
    expect(expected).toHaveLength(8);

    const session = await sessionWithCookie(cookie);
    // Type-level proof: `SessionUser` (the exported session type) declares `permissions`.
    const permissions: SessionUser["permissions"] | undefined = session?.user.permissions;
    expect(permissions).toEqual(expected);
  });

  it("drops a role grant the user has a DENY row for", async () => {
    const { userId, cookie } = await signedInAs("staff");
    const denied = await grantOf("1702");
    expect(denied).toEqual({ action: "read", subject: "Workflow" });
    expect((await sessionWithCookie(cookie))?.user.permissions).toContainEqual(denied);

    await prisma.userPermission.create({
      data: { userId, permissionKey: "1702", effect: "DENY" },
    });

    const session = await sessionWithCookie(cookie);
    expect(session?.user.permissions).not.toContainEqual(denied);
    expect(session?.user.permissions).toEqual(
      (await roleGrants("staff")).filter(
        (grant) => grant.action !== denied.action || grant.subject !== denied.subject,
      ),
    );
  });

  it("adds a grant the role lacks when the user has an ALLOW row for it", async () => {
    const { userId, cookie } = await signedInAs("staff");
    const allowed = await grantOf("1101");
    expect(allowed).toEqual({ action: "create", subject: "User" });
    expect((await sessionWithCookie(cookie))?.user.permissions).not.toContainEqual(allowed);

    await prisma.userPermission.create({
      data: { userId, permissionKey: "1101", effect: "ALLOW" },
    });

    const session = await sessionWithCookie(cookie);
    expect(session?.user.permissions).toContainEqual(allowed);
    expect(session?.user.permissions).toHaveLength(9);
  });

  it("carries every catalog grant (35) for a super_admin", async () => {
    const { cookie } = await signedInAs("super_admin");
    const expected = await roleGrants("super_admin");
    expect(expected).toHaveLength(35);

    const session = await sessionWithCookie(cookie);
    expect(session?.user.permissions).toEqual(expected);
  });
});
