import { afterAll, beforeAll, describe, expect, inject, it } from "vitest";

import { createPrismaClient } from "@repo/database";
import type { PrismaClient } from "@repo/database";
import { DEFAULT_ROLE } from "@repo/validation";

import { createAuth } from "../src/server";
import type { Auth, VerificationEmail } from "../src/server";

/**
 * Better Auth against a real Postgres: public sign-up is off, users come only from the admin
 * plugin's `createUser`, the verification mail goes through OUR callback (outbox in the API),
 * and sessions resolve from the cookie.
 */
let prisma: PrismaClient;
let auth: Auth;
const sentMails: VerificationEmail[] = [];

beforeAll(() => {
  prisma = createPrismaClient({ connectionString: inject("databaseUrl") });
  auth = createAuth({
    prisma,
    secret: "test-secret-test-secret-test-secret-1234",
    baseURL: "http://localhost:4000",
    trustedOrigins: ["http://localhost:3000"],
    sendVerificationEmail: (mail) => {
      sentMails.push(mail);
      return Promise.resolve();
    },
  });
});

afterAll(async () => {
  await prisma.$disconnect();
});

const PASSWORD = "correct-horse-battery";
const UUID_V7 = /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-/;

const unique = () => `user-${crypto.randomUUID()}@example.com`;

/** Server-side admin call (no headers): the only way a user gets created. */
const createUser = (email: string, name: string) =>
  auth.api.createUser({ body: { email, password: PASSWORD, name, role: DEFAULT_ROLE } });

/** The `better-auth.*` cookies of a response, as the `Cookie` header of the next request. */
const cookieHeaderFrom = (response: Response) =>
  response.headers
    .getSetCookie()
    .map((cookie) => cookie.split(";")[0] ?? "")
    .filter((cookie) => cookie.startsWith("better-auth."))
    .join("; ");

const sessionFor = (response: Response) =>
  auth.api.getSession({ headers: new Headers({ cookie: cookieHeaderFrom(response) }) });

describe("sign up", () => {
  it("is disabled: the public endpoint rejects and writes no user row", async () => {
    const email = unique();

    await expect(
      auth.api.signUpEmail({ body: { name: "Bat Bold", email, password: PASSWORD } }),
    ).rejects.toMatchObject({
      status: "BAD_REQUEST",
      body: { code: "EMAIL_PASSWORD_SIGN_UP_DISABLED" },
    });

    expect(await prisma.user.findUnique({ where: { email } })).toBeNull();
  });
});

describe("createUser (admin plugin, server-side)", () => {
  it("applies the default role when none is given and stores the name, a uuid v7 id and one credential account", async () => {
    const email = unique();

    // No `role` on purpose: the admin plugin's `defaultRole` must fill it in.
    const result = await auth.api.createUser({
      body: { email, password: PASSWORD, name: "Bat Bold" },
    });
    expect(result.user.email).toBe(email);

    const stored = await prisma.user.findUniqueOrThrow({ where: { email } });
    expect(stored).toMatchObject({ name: "Bat Bold", role: DEFAULT_ROLE, emailVerified: false });
    // UUID v7 generated by Postgres (generateId: false)
    expect(stored.id).toMatch(UUID_V7);

    const accounts = await prisma.account.findMany({ where: { userId: stored.id } });
    expect(accounts).toHaveLength(1);
    expect(accounts[0]?.providerId).toBe("credential");
  });

  it("rejects a role outside the role set and writes no user row", async () => {
    const email = unique();

    // The typed `role` field only admits configured keys; the endpoint validates `data.role`
    // on the same path, which is what an HTTP caller posting `role: "ceo"` hits.
    await expect(
      auth.api.createUser({
        body: { email, password: PASSWORD, name: "Nobody", data: { role: "ceo" } },
      }),
    ).rejects.toMatchObject({
      status: "BAD_REQUEST",
      body: { code: "YOU_ARE_NOT_ALLOWED_TO_SET_NON_EXISTENT_VALUE" },
    });

    expect(await prisma.user.findUnique({ where: { email } })).toBeNull();
  });
});

describe("email verification", () => {
  it("refuses to sign in before the email is verified", async () => {
    const email = unique();
    await createUser(email, "Unverified");

    await expect(
      auth.api.signInEmail({ body: { email, password: PASSWORD } }),
    ).rejects.toMatchObject({ status: "FORBIDDEN", body: { code: "EMAIL_NOT_VERIFIED" } });
  });

  it("sends exactly one mail through our callback, then verifies and issues a session", async () => {
    const email = unique();
    await createUser(email, "Verified");

    await auth.api.sendVerificationEmail({ body: { email } });

    const mails = sentMails.filter((mail) => mail.user.email === email);
    expect(mails).toHaveLength(1);
    expect(mails[0]?.user.name).toBe("Verified");
    expect(mails[0]?.url).toContain("/api/auth/verify-email");
    expect(mails[0]?.token.length).toBeGreaterThan(10);

    // autoSignInAfterVerification: the verify call returns Set-Cookie headers.
    const verifyResponse = await auth.api.verifyEmail({
      query: { token: mails[0]?.token ?? "" },
      asResponse: true,
    });
    expect(cookieHeaderFrom(verifyResponse)).toContain("better-auth.session_token");

    const session = await sessionFor(verifyResponse);
    expect(session?.user.email).toBe(email);
    expect(session?.user.emailVerified).toBe(true);
    expect(session?.user.role).toBe(DEFAULT_ROLE);
  });
});

describe("sessions", () => {
  it("signs in a user the admin created as verified and resolves the session from the cookie", async () => {
    const email = unique();
    await auth.api.createUser({
      body: {
        email,
        password: PASSWORD,
        name: "Pre-verified",
        role: DEFAULT_ROLE,
        data: { emailVerified: true },
      },
    });

    const signInResponse = await auth.api.signInEmail({
      body: { email, password: PASSWORD },
      asResponse: true,
    });
    expect(signInResponse.status).toBe(200);

    const session = await sessionFor(signInResponse);
    expect(session?.user.email).toBe(email);
    expect(session?.user.emailVerified).toBe(true);
    expect(session?.user.role).toBe(DEFAULT_ROLE);
  });

  it("resolves no session for a request without cookies", async () => {
    expect(await auth.api.getSession({ headers: new Headers() })).toBeNull();
  });
});
