import { reactConfig } from "@repo/eslint-config/react";
import { defineConfig } from "eslint/config";

export default defineConfig(reactConfig({ tsconfigRootDir: import.meta.dirname }), {
  // shadcn primitives are generated by the CLI (`npx shadcn add`) and kept pristine so they
  // can be re-generated; only our own code in components/composed follows the house style.
  files: ["src/components/*.tsx"],
  rules: { "func-style": "off", "import-x/consistent-type-specifier-style": "off" },
});
