import { reactConfig } from "@repo/eslint-config/react";
import { defineConfig } from "eslint/config";

export default defineConfig(reactConfig({ tsconfigRootDir: import.meta.dirname }), {
  // shadcn primitives are generated by the CLI (`npx shadcn add`) and kept pristine so they
  // can be re-generated; only our own code in components/composed follows the house style.
  files: ["src/components/*.tsx"],
  rules: {
    "func-style": "off",
    "import-x/consistent-type-specifier-style": "off",
    "@typescript-eslint/no-unnecessary-condition": "off",
    "@eslint-react/no-leaked-conditional-rendering": "off",
    "@eslint-react/no-array-index-key": "off",
    "@eslint-react/no-nested-component-definitions": "off",
    eqeqeq: "off",
  },
});
